### ISSUE TITLE
can AWR1642ODS get the 3d position？

### ISSUE THREAD

**Issue by YihanExile** [jiheddachraoui/AWR1642-cloud-point-reader#1]
recently i need to use awr1642ods to collect some data for my research. basically i know nothing about the hardware. i use some open source code to read data from the borad, but the  z coordinates always are zero. could u please tell me whether the board can read 3d position data？thank u

**Comment by jiheddachraoui** [comment]
hello yihan, so the code provided here is for AWR1642boost: The antennas on the 1642boost are all aligned in the azimuth plan, so there is no angle measurement possible on the elevation plan (in the direction of the blue line). So all the objects in that plan will show up at 0deg elevation itself.
Now talking about awr1642ods  it does have both azimuth and elevation planes, and is suited for automotive applications where detection of objects is needed in near-range 3D space,

**Comment by jiheddachraoui** [comment]
Hello Yihan! I wanted to share some information about the code provided for AWR1642boost. On the AWR1642boost, the antennas are positioned in such a way that they are all aligned in the azimuth plane. As a result, it is not possible to measure angles in the elevation plane (the direction of the blue line). Consequently, all objects in that plane will appear at an elevation of 0 degrees.
![image](https://github.com/jiheddachraoui/AWR1642-cloud-point-reader/assets/93733459/4288b38f-783d-4e2e-95a3-81f13f5480e5)


On the other hand, the AWR1642ods is designed with both azimuth and elevation planes, making it suitable for automotive applications that require object detection in the near-range 3D space. I recommend checking out this link for more information:
#https://github.com/ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-/issues/26

**Comment by YihanExile** [comment]
thanks a lot！！！

**Comment by jiheddachraoui** [comment]
you are welcome .
i forgot to upload the picture , you can see it now
